# _config.yml
title: 부동산의 모든 것
url: https://kimkisaa.github.io
baseurl: /land
lang: ko
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# 사이트 로고(구조화 데이터용)
logo: /og-image.jpg
defaults:
  - scope: { path: "", type: "pages" }
    values:
      image: /og-image.jpg
